import {
  Box,
  Heading,
  Table,
  Thead,
  Tbody,
  Tr,
  Th,
  Td,
  TableContainer,
  useColorModeValue,
  Button,
  useDisclosure,
  useToast,
} from "@chakra-ui/react";

import { useEffect, useState, useRef, useCallback, useMemo, memo, } from "react";
import { getReportHistory, deleteReportHistory } from "../../services/reportService";
import ReportDetailsModal from "./ReportDetailsModal";
import ConfirmDialog from '../common/ConfirmDialog';
import StatusBadge from '../common/StatusBadge';
import EmptyState from '../common/EmptyState';
import SearchBar from '../common/SearchBar';
import LoadingSkeleton from '../common/LoadingSkeleton';
import { useAuth } from "../../context/AuthContext";

function ReportHistoryTable() {
  const [reports, setReports] = useState([]);
  const [search, setSearch] = useState("");
  const [deleteReport, setDeleteReport] = useState(null);

  const cancelRef = useRef();

  const {
    isOpen: isDeleteOpen,
    onOpen: onDeleteOpen,
    onClose: onDeleteClose,
  } = useDisclosure();
  const [loading, setLoading] = useState(true);
  const {
    isOpen,
    onOpen,
    onClose,
  } = useDisclosure();

  const { user } = useAuth();

  const toast = useToast();

  const [selectedReport, setSelectedReport] = useState(null);

  const cardBg = useColorModeValue(
    "white",
    "gray.800"
  );
  const hoverBg = useColorModeValue(
    "gray.50",
    "gray.700"
  );

  const loadReports = useCallback(async () => {
    try {
      const data = await getReportHistory();
      setReports(data.reports);
    } catch (error) {
      console.error(error);
    } finally {
      setLoading(false);
    }
  },[]);

  useEffect(() => {
    loadReports();
  }, [loadReports]);

  const handleView = (report) => {
    setSelectedReport(report);
    onOpen();
  };

  const handleDeleteClick = (report) => {
    setDeleteReport(report);
    onDeleteOpen();
  };

  const handleDelete = async (id) => {
    try {
      const data = await deleteReportHistory(id);
      toast({
        title: data.message,
        status: "success",
        duration: 3000,
      });
      loadReports();
    } catch (error) {
      toast({
        title:
          error.response?.data?.message ||
          "Delete failed",
        status: "error",
        duration: 3000,
      });
    }
  };

  const filteredReports = useMemo(() => {
    return reports.filter((report) => {
      const name = report.generatedBy?.name || "";

      return (
        name
          .toLowerCase()
          .includes(search.toLowerCase()) ||

        report.format
          .toLowerCase()
          .includes(search.toLowerCase())
      );
    });
  }, [reports, search]);

  if (loading) {
    return (
      <LoadingSkeleton />
    );
  }

  return (
    <Box
      bg={cardBg}
      p={6}
      rounded="lg"
      shadow="md"
      mt={6}
    >
      <Heading size="md" mb={5}>
        📜 Generated Report History ({filteredReports.length})
      </Heading>

      <Box
          display="flex"
          justifyContent="space-between"
          alignItems="center"
          mb={5}
        >
          <SearchBar
            value={search}
            onChange={setSearch}
            placeholder="Search by user or format..."
        />

          <Button
            colorScheme="blue"
            onClick={loadReports}
            isLoading={loading}
          >
            Refresh
          </Button>
        </Box>

      <TableContainer>
        <Table variant="simple">

          <Thead>
            <Tr>
              <Th>Format</Th>
              <Th>Generated By</Th>
              <Th>Total Logs</Th>
              <Th>Severity</Th>
              <Th>Threat Type</Th>
              <Th>Date</Th>
              <Th>Action</Th>
            </Tr>
          </Thead>

          <Tbody>

            {filteredReports.length === 0 ? (

              <Tr>
                <Td colSpan={7}>
                  <EmptyState
                    title="No Reports Found"
                    description="Try changing your search or generate a new report."
                  />
                </Td>
              </Tr>

            ):(

            filteredReports.map((report) => (
              <Tr
                key={report._id}
                _hover={{
                  bg: hoverBg,
                }}
              >

                <Td>
                  <StatusBadge
                    value={report.format}
                    type="format"
                  />
                </Td>

                <Td>
                  {report.generatedBy?.name || "-"}
                </Td>

                <Td>
                  {report.totalLogs}
                </Td>

                <Td>
                  {report.severity || "-"}
                </Td>

                <Td>
                  {report.threatType || "-"}
                </Td>

                <Td>
                  {new Date(
                    report.createdAt
                  ).toLocaleString()}
                </Td>

                <Td>
                  <Button
                    size="sm"
                    colorScheme="blue"
                    onClick={() =>
                      handleView(report)
                    }
                    mr={2}
                  >
                    View
                  </Button>

                  {user.role === "Admin" && (
                    <Button
                      size="sm"
                      colorScheme="red"
                      onClick={() =>
                        handleDeleteClick(report)
                      }
                    >
                      Delete
                    </Button>
                  )}
                </Td>

              </Tr>
            ))
          )}

          </Tbody>

        </Table>
      </TableContainer>
      <ReportDetailsModal
        isOpen={isOpen}
        onClose={onClose}
        report={selectedReport}
      />

      <ConfirmDialog
        isOpen={isDeleteOpen}
        onClose={onDeleteClose}
        cancelRef={cancelRef}
        title="Delete Report"
        message={
          <>
            Are you sure you want to delete this report?

            <br /><br />

            <strong>Format:</strong>{" "}
            {deleteReport?.format}

            <br />

            <strong>Generated By:</strong>{" "}
            {deleteReport?.generatedBy?.name}
          </>
        }
        onConfirm={() => {
          handleDelete(deleteReport._id);
          onDeleteClose();
        }}
      />

    </Box>
  );
}

export default memo(ReportHistoryTable);