import {
  Modal,
  ModalOverlay,
  ModalContent,
  ModalHeader,
  ModalCloseButton,
  ModalBody,
  Text,
  VStack,
  HStack,
} from "@chakra-ui/react";
import { memo } from "react";
import StatusBadge from "../common/StatusBadge";

function ReportDetailsModal({
  isOpen,
  onClose,
  report,
}) {
  if (!report) return null;

  return (
    <Modal isOpen={isOpen} onClose={onClose}>
      <ModalOverlay />

      <ModalContent maxH="80vh">
        <ModalHeader>
          Generated Report Details
        </ModalHeader>

        <ModalCloseButton />

        <ModalBody pb={6} overflowY="auto">
          <VStack align="start" spacing={3}>

            <HStack justify="space-between" w="100%">
              <Text fontWeight="bold">
                Format
              </Text>

              <StatusBadge
                value={report.format}
                type="format"
              />
            </HStack>

            <HStack justify="space-between" w="100%">
              <Text fontWeight="bold">
                Generated By
              </Text>

              <Text>
                {report.generatedBy?.name || "-"}
              </Text>
            </HStack>

            <HStack justify="space-between" w="100%">
              <Text fontWeight="bold">
                Email
              </Text>

              <Text>
                {report.generatedBy?.email || "-"}
              </Text>
            </HStack>

            <HStack justify="space-between" w="100%">
              <Text fontWeight="bold">
                Total Logs
              </Text>

              <Text>
                {report.totalLogs}
              </Text>
            </HStack>

            <HStack justify="space-between" w="100%">
              <Text fontWeight="bold">
                Severity
              </Text>

              <Text>
                {report.severity || "-"}
              </Text>
            </HStack>

            <HStack justify="space-between" w="100%">
              <Text fontWeight="bold">
                Threat Type
              </Text>

              <Text>
                {report.threatType || "-"}
              </Text>
            </HStack>

            <HStack justify="space-between" w="100%">
              <Text fontWeight="bold">
                Generated On
              </Text>

              <Text>
                {new Date(report.createdAt).toLocaleString()}
              </Text>
            </HStack>

          </VStack>
        </ModalBody>

      </ModalContent>
    </Modal>
  );
}

export default memo(ReportDetailsModal);