import {
  Box,
  Heading,
  Spinner,
  Center,
  Table,
  Thead,
  Tbody,
  Tr,
  Th,
  Td,
  Badge,
  TableContainer,
  useColorModeValue,
  Button,
  useDisclosure,
  useToast,
  Input,
  AlertDialog,
  AlertDialogBody,
  AlertDialogContent,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogOverlay,
} from "@chakra-ui/react";

import { useEffect, useState, useRef } from "react";
import { getReportHistory, deleteReportHistory } from "../../services/reportService";
import ReportDetailsModal from "./ReportDetailsModal";
import ConfirmDialog from '../common/ConfirmDialog';
import StatusBadge from '../common/StatusBadge';
import { useAuth } from "../../context/AuthContext";

function ReportHistoryTable() {
  const [reports, setReports] = useState([]);
  const [search, setSearch] = useState("");
  const [deleteReport, setDeleteReport] = useState(null);

  const cancelRef = useRef();

  const {
    isOpen: isDeleteOpen,
    onOpen: onDeleteOpen,
    onClose: onDeleteClose,
  } = useDisclosure();
  const [loading, setLoading] = useState(true);
  const {
    isOpen,
    onOpen,
    onClose,
  } = useDisclosure();

  const { user } = useAuth();

  const toast = useToast();

  const [selectedReport, setSelectedReport] = useState(null);

  const cardBg = useColorModeValue(
    "white",
    "gray.800"
  );

  useEffect(() => {
    loadReports();
  }, []);

  const handleView = (report) => {
    setSelectedReport(report);
    onOpen();
  };

  const handleDeleteClick = (report) => {
    setDeleteReport(report);
    onDeleteOpen();
  };

  const handleDelete = async (id) => {
    try {
      const data = await deleteReportHistory(id);
      toast({
        title: data.message,
        status: "success",
        duration: 3000,
      });
      loadReports();
    } catch (error) {
      toast({
        title:
          error.response?.data?.message ||
          "Delete failed",
        status: "error",
        duration: 3000,
      });
    }
  };

  const loadReports = async () => {
    try {
      const data = await getReportHistory();
      setReports(data.reports);
    } catch (error) {
      console.error(error);
    } finally {
      setLoading(false);
    }
  };

  if (loading) {
    return (
      <Center h="250px">
        <Spinner size="lg" />
      </Center>
    );
  }

  const filteredReports = reports.filter((report) => {
    const name =
      report.generatedBy?.name || "";

    return (
      name
        .toLowerCase()
        .includes(search.toLowerCase()) ||

      report.format
        .toLowerCase()
        .includes(search.toLowerCase())
    );
  });

  return (
    <Box
      bg={cardBg}
      p={6}
      rounded="lg"
      shadow="md"
      mt={6}
    >
      <Heading size="md" mb={5}>
        📜 Generated Report History ({filteredReports.length})
      </Heading>

      <Box
          display="flex"
          justifyContent="space-between"
          alignItems="center"
          mb={5}
        >
          <Input
            placeholder="Search by user or format..."
            value={search}
            onChange={(e) =>
              setSearch(e.target.value)
            }
            maxW="400px"
          />

          <Button
            colorScheme="blue"
            onClick={loadReports}
          >
            Refresh
          </Button>
        </Box>

      <TableContainer>
        <Table variant="simple">

          <Thead>
            <Tr>
              <Th>Format</Th>
              <Th>Generated By</Th>
              <Th>Total Logs</Th>
              <Th>Severity</Th>
              <Th>Threat Type</Th>
              <Th>Date</Th>
              <Th>Action</Th>
            </Tr>
          </Thead>

          <Tbody>

            {filteredReports.length === 0 ? (

              <Tr>
                <Td
                  colSpan={6}
                  textAlign="center"
                >
                  <Box py={10} textAlign="center">
                    No reports match your search.
                  </Box>
                </Td>
              </Tr>

            ):(

            filteredReports.map((report) => (
              <Tr key={report._id}>

                <Td>
                  <StatusBadge
                    value={report.format}
                    type="format"
                  />
                </Td>

                <Td>
                  {report.generatedBy?.name}
                </Td>

                <Td>
                  {report.totalLogs}
                </Td>

                <Td>
                  {report.severity}
                </Td>

                <Td>
                  {report.threatType}
                </Td>

                <Td>
                  {new Date(
                    report.createdAt
                  ).toLocaleString()}
                </Td>

                <Td>
                  <Button
                    size="sm"
                    colorScheme="blue"
                    onClick={() =>
                      handleView(report)
                    }
                  >
                    View
                  </Button>

                  {user.role === "Admin" && (
                    <Button
                      size="sm"
                      colorScheme="red"
                      onClick={() =>
                        handleDeleteClick(report)
                      }
                    >
                      Delete
                    </Button>
                  )}
                </Td>

              </Tr>
            ))
          )}

          </Tbody>

        </Table>
      </TableContainer>
      <ReportDetailsModal
        isOpen={isOpen}
        onClose={onClose}
        report={selectedReport}
      />

      <ConfirmDialog
        isOpen={isDeleteOpen}
        onClose={onDeleteClose}
        cancelRef={cancelRef}
        title="Delete Report"
        message={
          <>
            Are you sure you want to delete this report?

            <br /><br />

            <strong>Format:</strong>{" "}
            {deleteReport?.format}

            <br />

            <strong>Generated By:</strong>{" "}
            {deleteReport?.generatedBy?.name}
          </>
        }
        onConfirm={() => {
          handleDelete(deleteReport._id);
          onDeleteClose();
        }}
      />

    </Box>
  );
}

export default ReportHistoryTable;