import {
  Modal,
  ModalOverlay,
  ModalContent,
  ModalHeader,
  ModalCloseButton,
  ModalBody,
  Text,
  VStack,
} from "@chakra-ui/react";

function ReportDetailsModal({
  isOpen,
  onClose,
  report,
}) {
  if (!report) return null;

  return (
    <Modal isOpen={isOpen} onClose={onClose}>
      <ModalOverlay />

      <ModalContent>
        <ModalHeader>
          Report Details
        </ModalHeader>

        <ModalCloseButton />

        <ModalBody pb={6}>
          <VStack align="start" spacing={3}>

            <Text>
              <strong>Format:</strong> {report.format}
            </Text>

            <Text>
              <strong>Generated By:</strong>{" "}
              {report.generatedBy?.name}
            </Text>

            <Text>
              <strong>Email:</strong>{" "}
              {report.generatedBy?.email}
            </Text>

            <Text>
              <strong>Total Logs:</strong>{" "}
              {report.totalLogs}
            </Text>

            <Text>
              <strong>Severity:</strong>{" "}
              {report.severity}
            </Text>

            <Text>
              <strong>Threat Type:</strong>{" "}
              {report.threatType}
            </Text>

            <Text>
              <strong>Generated On:</strong>{" "}
              {new Date(
                report.createdAt
              ).toLocaleString()}
            </Text>

          </VStack>
        </ModalBody>

      </ModalContent>
    </Modal>
  );
}

export default ReportDetailsModal;