const threatAlertTemplate = (log) => {
  const priorityColor =
    log.priority === "Critical"
      ? "#d32f2f"
      : log.priority === "High"
      ? "#f57c00"
      : log.priority === "Medium"
      ? "#fbc02d"
      : "#388e3c";

  return `
<!DOCTYPE html>
<html>

<head>
  <meta charset="UTF-8">
  <title>SOC Threat Alert</title>
</head>

<body
  style="
    font-family: Arial, Helvetica, sans-serif;
    background:#f5f5f5;
    margin:0;
    padding:20px;
  "
>

  <div
    style="
      max-width:650px;
      margin:auto;
      background:#ffffff;
      border-radius:10px;
      padding:30px;
      box-shadow:0 2px 8px rgba(0,0,0,.1);
    "
  >

    <h2
      style="
        color:#d32f2f;
        margin-top:0;
      "
    >
      🚨 SOC Threat Alert
    </h2>

    <p>
      A potential security threat has been detected by
      <strong>SOC Log Analyzer</strong>.
    </p>

    <hr>

    <table
      width="100%"
      cellpadding="8"
      cellspacing="0"
      style="border-collapse:collapse;"
    >

      <tr>
        <td><strong>Threat</strong></td>
        <td>${log.threatType || "N/A"}</td>
      </tr>

      <tr>
        <td><strong>Priority</strong></td>
        <td>
          <span
            style="
              color:${priorityColor};
              font-weight:bold;
            "
          >
            ${log.priority || "N/A"}
          </span>
        </td>
      </tr>

      <tr>
        <td><strong>Severity</strong></td>
        <td>${log.severity || "N/A"}</td>
      </tr>

      <tr>
        <td><strong>Threat Score</strong></td>
        <td>${log.threatScore ?? "N/A"}</td>
      </tr>

      <tr>
        <td><strong>IP Address</strong></td>
        <td>${log.ip || "N/A"}</td>
      </tr>

      <tr>
        <td><strong>Timestamp</strong></td>
        <td>${log.timestamp || "N/A"}</td>
      </tr>

      <tr>
        <td><strong>MITRE ATT&CK</strong></td>
        <td>${log.mitreTechnique || "N/A"}</td>
      </tr>

      <tr>
        <td><strong>Description</strong></td>
        <td>${log.description || "N/A"}</td>
      </tr>

    </table>

    <hr>

    <p
      style="
        color:#666;
        font-size:14px;
        line-height:1.6;
      "
    >
      This is an automated security notification generated by
      <strong>SOC Log Analyzer</strong>.
    </p>

    <p
      style="
        color:#666;
        font-size:14px;
      "
    >
      Please investigate this event if necessary.
    </p>

  </div>

</body>

</html>
`;
};

module.exports = threatAlertTemplate;