import {
  Box,
  Heading,
  Text,
  VStack,
  List,
  ListItem,
  ListIcon,
  useColorModeValue,
} from "@chakra-ui/react";

import { CheckCircleIcon } from "@chakra-ui/icons";

function AboutRoleCard() {
  const bg = useColorModeValue("white", "gray.800");

  return (
    <Box
      bg={bg}
      p={6}
      rounded="lg"
      shadow="md"
      mt={6}
    >
      <Heading size="md" mb={5}>
        ℹ️ About Your Role
      </Heading>

      <Text mb={4}>
        As an <strong>Analyst</strong>, you are responsible for monitoring,
        investigating and responding to security events generated by the SOC
        Log Analyzer.
      </Text>

      <VStack align="stretch">
        <List spacing={3}>
          <ListItem>
            <ListIcon as={CheckCircleIcon} color="green.500" />
            Upload and analyze log files
          </ListItem>

          <ListItem>
            <ListIcon as={CheckCircleIcon} color="green.500" />
            Monitor live log activity
          </ListItem>

          <ListItem>
            <ListIcon as={CheckCircleIcon} color="green.500" />
            Investigate detected threats
          </ListItem>

          <ListItem>
            <ListIcon as={CheckCircleIcon} color="green.500" />
            Generate investigation reports
          </ListItem>

          <ListItem>
            <ListIcon as={CheckCircleIcon} color="green.500" />
            Review attack origins and threat statistics
          </ListItem>
        </List>
      </VStack>
    </Box>
  );
}

export default AboutRoleCard;